language: java
jdk:
  - openjdk8

branches:
  only:
    - ci

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'


script:
  - "./gradlew clean build"

# 배포에 필요한 파일들만 archive 에 옮겨서 archive/archive.zip 파일로 만든다.
before_deploy:
  - mkdir -p deploy
  - cp build/libs/*.jar deploy/application.jar
  - cp Procfile deploy/Procfile
  - cp -r ./.ebextensions deploy/.ebextensions
  - cd deploy && zip -r deploy.zip .

deploy:
  provider: elasticbeanstalk
  zip_file: deploy.zip
  skip_cleanup: true
  access_key_id: $AWS_ACCESS_KEY # declared in Travis repo settings
  secret_access_key: $AWS_SECRET_KEY
  region: "ap-northeast-2"
  app: "restaurant"
  env: "Restaurant-java8"
  bucket_name: "elasticbeanstalk-ap-northeast-2-893382876075"  # S3 bucket name
  on:
    branch: ci

after_deploy:
  - echo "Elastic Beanstalk 배포 진행중입니다."